DoAn_CuaHangLaptop/Test/Models/Congketnoi.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace Test.Models
{
    public partial class Congketnoi
    {
        public Congketnoi()
        {
            Sanpham = new HashSet<Sanpham>();
        }
        [Display(Name = "Mã cổng kết nối")]
        public string Mackn { get; set; }
        [Display(Name = "Cổng giao tiếp")]
        public string Conggiaotiep { get; set; }
        [Display(Name = "Kết nối không dây")]
        public string Ketnoikhongday { get; set; }
        [Display(Name = "Khe đọc thẻ nhớ")]
        public string Khedocthenho { get; set; }
        [Display(Name = "Webcam")]
        public string Webcam { get; set; }
        [Display(Name = "Tính năng khác")]
        public string Tinhnangkhac { get; set; }
        [Display(Name = "Đèn bàn phím")]
        public string Denbanphim { get; set; }

        public virtual ICollection<Sanpham> Sanpham { get; set; }
    }
}

DoAn_CuaHangLaptop/Test/Areas/Admin/Controllers/CongKetNoiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Test.Data;
using Test.Models;

namespace Test.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "admin")]
    public class CongKetNoiController : Controller
    {
        private readonly LapTopContext _context;

        public CongKetNoiController(LapTopContext context)
        {
            _context = context;
        }

        // GET: Congketnois
        public async Task<IActionResult> Index()
        {
            return View(await _context.Congketnoi.ToListAsync());
        }

        // GET: Congketnois/Details/5
        //public async Task<IActionResult> Details(string id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var congketnoi = await _context.Congketnoi
        //        .FirstOrDefaultAsync(m => m.Mackn == id);
        //    if (congketnoi == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(congketnoi);
        //}

        // GET: Congketnois/Create
        //public IActionResult Create()
        //{
        //    return View();
        //}

        // POST: Congketnois/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Mackn,Conggiaotiep,Ketnoikhongday,Khedocthenho,Webcam,Tinhnangkhac,Denbanphim")] Congketnoi congketnoi)
        {
            if (ModelState.IsValid)
            {
                _context.Add(congketnoi);
                await _context.SaveChangesAsync();
                TempData["AlertMessage"] = "Tạo thành công";
                TempData["AlertType"] = "alert alert-success";
                return RedirectToAction(nameof(Index));
            }
            return View(congketnoi);
        }

        // GET: Congketnois/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var congketnoi = await _context.Congketnoi.FindAsync(id);
            if (congketnoi == null)
            {
                return NotFound();
            }
            return View(congketnoi);
        }

        // POST: Congketnois/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Mackn,Conggiaotiep,Ketnoikhongday,Khedocthenho,Webcam,Tinhnangkhac,Denbanphim")] Congketnoi congketnoi)
        {
            if (id != congketnoi.Mackn)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(congketnoi);
                    await _context.SaveChangesAsync();
                    TempData["AlertMessage"] = "Cập nhật thành công";
                    TempData["AlertType"] = "alert alert-success";
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CongketnoiExists(congketnoi.Mackn))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(congketnoi);
        }

        // GET: Congketnois/Delete/5
        //public async Task<IActionResult> Delete(string id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var congketnoi = await _context.Congketnoi
        //        .FirstOrDefaultAsync(m => m.Mackn == id);
        //    if (congketnoi == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(congketnoi);
        //}

        // POST: Congketnois/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(string Mackn)
        {
            try
            {
                var congketnoi = await _context.Congketnoi.FindAsync(Mackn);
                _context.Congketnoi.Remove(congketnoi);
                await _context.SaveChangesAsync();
                TempData["AlertMessage"] = "Xóa thành công";
                TempData["AlertType"] = "alert alert-success";
                return RedirectToAction(nameof(Index));

            }
            catch
            {
                TempData["AlertMessage"] = "Xóa không thành công";
                TempData["AlertType"] = "alert alert-danger";
                return RedirectToAction(nameof(Index));
            }
        }

        private bool CongketnoiExists(string id)
        {
            return _context.Congketnoi.Any(e => e.Mackn == id);
        }
        [HttpPost]
        public JsonResult timCongKetNoi(string id)
        {
            var ckn = _context.Congketnoi.Find(id); ;
            return Json(ckn);
        }
    }
}

DoAn_CuaHangLaptop/Test/Areas/Admin/Pages/Role/edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Test.Data;

namespace App.Admin.Role
{
    [Authorize(Roles = "admin")]

    public class EditModel : RolePageModel
    {
        public EditModel(RoleManager<IdentityRole> roleManager, LapTopContext myBlogContext) : base(roleManager, myBlogContext)
        {

        }

        public class InputModel
        {
            [Display(Name = "Tên của role")]
            [Required(ErrorMessage = "Phải nhập {0}")]
            [StringLength(256, MinimumLength = 3, ErrorMessage = "{0} phải dài {2} đến {1} ký tự")]
            public string Name { get; set; }
        }

        [BindProperty]
        public InputModel Input { set; get; }

        public IdentityRole role { get; set; }

        public async Task<IActionResult> OnGet(string roleid)
        {
            if (roleid == null) return NotFound("Không tìm thấy role");

            role = await _roleManager.FindByIdAsync(roleid);
            if (role != null)
            {
                Input = new InputModel()
                {
                    Name = role.Name
                };
                return Page();
            }
            return NotFound("Không tìm thấy role");
        }



        public async Task<IActionResult> OnPostAsync(string roleid)
        {
            if (roleid == null) return NotFound("Không tìm thấy role");
            role = await _roleManager.FindByIdAsync(roleid);
            if (role == null) return NotFound("Không tìm thấy role");
            if (!ModelState.IsValid)
            {
                return Page();
            }

            role.Name = Input.Name;
            // luu ket qua cap nhat trong result
            var result = await _roleManager.UpdateAsync(role);

            if (result.Succeeded)
            {
                StatusMessage = $"Bạn vừa đổi tên: {Input.Name}";
                return RedirectToPage("./Index");
            }
            else
            {
                result.Errors.ToList().ForEach(error => {
                    ModelState.AddModelError(string.Empty, error.Description);
                });
            }
            return Page();
        }
    }
}

DoAn_CuaHangLaptop/Test/Controllers/CongketnoisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Test.Data;
using Test.Models;

namespace Test.Controllers
{
    public class CongketnoisController : Controller
    {
        private readonly LapTopContext _context;

        public CongketnoisController(LapTopContext context)
        {
            _context = context;
        }

        // GET: Congketnois
        public async Task<IActionResult> Index()
        {
            return View(await _context.Congketnoi.ToListAsync());
        }

        // GET: Congketnois/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var congketnoi = await _context.Congketnoi
                .FirstOrDefaultAsync(m => m.Mackn == id);
            if (congketnoi == null)
            {
                return NotFound();
            }

            return View(congketnoi);
        }

        // GET: Congketnois/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Congketnois/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Mackn,Conggiaotiep,Ketnoikhongday,Khedocthenho,Webcam,Tinhnangkhac,Denbanphim")] Congketnoi congketnoi)
        {
            if (ModelState.IsValid)
            {
                _context.Add(congketnoi);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(congketnoi);
        }

        // GET: Congketnois/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var congketnoi = await _context.Congketnoi.FindAsync(id);
            if (congketnoi == null)
            {
                return NotFound();
            }
            return View(congketnoi);
        }

        // POST: Congketnois/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Mackn,Conggiaotiep,Ketnoikhongday,Khedocthenho,Webcam,Tinhnangkhac,Denbanphim")] Congketnoi congketnoi)
        {
            if (id != congketnoi.Mackn)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(congketnoi);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CongketnoiExists(congketnoi.Mackn))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(congketnoi);
        }

        // GET: Congketnois/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var congketnoi = await _context.Congketnoi
                .FirstOrDefaultAsync(m => m.Mackn == id);
            if (congketnoi == null)
            {
                return NotFound();
            }

            return View(congketnoi);
        }

        // POST: Congketnois/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var congketnoi = await _context.Congketnoi.FindAsync(id);
            _context.Congketnoi.Remove(congketnoi);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CongketnoiExists(string id)
        {
            return _context.Congketnoi.Any(e => e.Mackn == id);
        }
    }
}

DoAn_CuaHangLaptop/Test/Areas/Admin/Views/CongKetNoi/Edit.cshtml
@model Test.Models.Congketnoi

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h1>Cập nhật</h1>

<h4>Cổng kết nối</h4>
<hr />
<div class="row" style="display:flex;justify-content:center">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Mackn" />
            <div class="form-group">
                <label asp-for="Conggiaotiep" class="control-label"></label>
                <input asp-for="Conggiaotiep" class="form-control" />
                <span asp-validation-for="Conggiaotiep" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ketnoikhongday" class="control-label"></label>
                <input asp-for="Ketnoikhongday" class="form-control" />
                <span asp-validation-for="Ketnoikhongday" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Khedocthenho" class="control-label"></label>
                <input asp-for="Khedocthenho" class="form-control" />
                <span asp-validation-for="Khedocthenho" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Webcam" class="control-label"></label>
                <input asp-for="Webcam" class="form-control" />
                <span asp-validation-for="Webcam" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tinhnangkhac" class="control-label"></label>
                <input asp-for="Tinhnangkhac" class="form-control" />
                <span asp-validation-for="Tinhnangkhac" class="text-danger"></span>
            </div>
            <div class="form-row">
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="Denbanphim" id="Denbanphim" value="có" checked>
                    <label class="form-check-label" for="Denbanphim">
                        Có đèn bàn phím
                    </label>
                </div>
                <div class="form-group col-md-1">
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="Denbanphim" id="Denbanphim" value="không">
                    <label class="form-check-label" for="Denbanphim">
                        Không có đèn bàn phím
                    </label>
                </div>
            </div>
            @*<div class="form-group">
                <label asp-for="Denbanphim" class="control-label"></label>
                <input asp-for="Denbanphim" class="form-control" />
                <span asp-validation-for="Denbanphim" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <input type="submit" value="Lưu" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="mt-3">Trở về trang danh sách</a>
</div>

DoAn_CuaHangLaptop/Test/Areas/Admin/Views/CongKetNoi/Index.cshtml
@model IEnumerable<Test.Models.Congketnoi>
@{
    Layout = "_Layout";
}
@section Scripts{
    <script>
    setTimeout(function () {
        $('#msgA').fadeOut('slow');
    }, 2000);
    $('table .delete').on('click', function () {
        var id = $(this).data("id");
            $.ajax({
                type: 'POST',
                url: '@Url.Action("timCongKetNoi")',
                data: { "id": id },
                success: function (response) {
                    console.log(response)
                    $("#DeleteRecord #Mackn").val(response.mackn);
                    $("#DeleteRecord #Conggiaotiep").val(response.conggiaotiep);
                    $("#DeleteRecord #Ketnoikhongday").val(response.ketnoikhongday);
                    $("#DeleteRecord #Webcam").val(response.webcam);
                }
            })
    })
    </script>
}
<div class="container-fluid">

    <!-- Page Heading -->
    <!-- DataTales Example -->
    <div class="card shadow mb-4">

        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Cổng kết nối</h6>
        </div>

        <p></p>

        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <form asp-action="Create" method="post">
                        <input type="hidden" class="form-control" id="Mackn" name="Mackn" value="1">
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <label for="Conggiaotiep">Cổng giao tiếp</label>
                                <textarea class="form-control" id="Conggiaotiep" name="Conggiaotiep" rows="3"></textarea>
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <label for="Ketnoikhongday">Kết nối không dây</label>
                                <textarea class="form-control" id="Ketnoikhongday" name="Ketnoikhongday" rows="3"></textarea>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <label for="Khedocthenho">Khe đọc thẻ nhớ</label>
                                <textarea class="form-control" id="Khedocthenho" name="Khedocthenho" rows="3"></textarea>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="Denbanphim" id="Denbanphim" value="có" checked>
                                <label class="form-check-label" for="Denbanphim">
                                    Có đèn bàn phím
                                </label>
                            </div>
                            <div class="form-group col-md-1">
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="Denbanphim" id="Denbanphim" value="không">
                                <label class="form-check-label" for="Denbanphim">
                                    Không có đèn bàn phím
                                </label>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <label for="Tinhnangkhac">Webcam</label>
                                <textarea class="form-control" id="Webcam" name="Webcam" rows="3"></textarea>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <label for="Tinhnangkhac">Tính năng khác</label>
                                <textarea class="form-control" id="Tinhnangkhac" name="Tinhnangkhac" rows="3"></textarea>
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="form-group col-md-10"></div>
                            <div class="form-group col-md-2 center">
                                <button type="submit" class="btn btn-primary">Thêm</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        @if (TempData["AlertMessage"] != null)
        {
            <div id="msgA" class="@TempData["AlertType"]" role="alert">
                @TempData["AlertMessage"]
            </div>
        }
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th width="25%">Cổng giao tiếp</th>
                            <th width="20%">Kết nối không dây</th>
                            <th width="10%">Đầu đọc thẻ nhớ</th>
                            <th width="10%">Webcam </th>
                            <th width="10%">Tính năng khác</th>
                            <th width="10%">Đèn bàn phím</th>
                            <th width="15%">Tác vụ</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                        <tr>
                            <td>@item.Conggiaotiep</td>
                            <td>@item.Ketnoikhongday</td>
                            <td>@item.Khedocthenho</td>
                            <td>@item.Webcam</td>
                            <td>@item.Tinhnangkhac</td>
                            <td>@item.Denbanphim</td>
                            <td>
                                <a asp-action="Edit" asp-route-id="@item.Mackn" class="btn btn-secondary">Cập nhật</a>
                                <button type="button"
                                        class="btn btn-danger delete"
                                        data-toggle="modal"
                                        data-target="#DeleteRecord"
                                        data-id="@item.Mackn">
                                    Xóa
                                </button>
                            </td>
                        </tr>
                        }

                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>
<div class="modal fade" id="DeleteRecord" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Xác nhận xóa</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form asp-controller="CongKetNoi" asp-action="Delete" method="post">
                <div class="modal-body">
                    <div class="form-group">
                        <input type="hidden" readonly id=Mackn class="form-control" name="Mackn" />

                        <div class="form-group row">
                            <label class="col-sm-4 col-form-label">Cổng giao tiếp</label>
                            <div class="col-sm-8">
                                <input type="text" readonly id="Conggiaotiep" class="form-control" name="Conggiaotiep" />
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-sm-4 col-form-label">Kết nối không dây</label>
                            <div class="col-sm-8">
                                <input type="text" readonly id="Ketnoikhongday" class="form-control" name="Ketnoikhongday" />
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-sm-4 col-form-label">Webcam</label>
                            <div class="col-sm-8">
                                <input type="text" readonly id="Webcam" class="form-control" name="Webcam" />
                            </div>
                        </div>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Đóng</button>

                    <button type="submit" class="btn btn-primary">Xóa</button>
                </div>
            </form>
        </div>
    </div>
</div>