DoAn_CuaHangLaptop/Test/Models/Hoadon.cs
using System;
using System.Collections.Generic;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace Test.Models
{
    public partial class Hoadon
    {
        public Hoadon()
        {
            Cthd = new HashSet<Cthd>();
        }

        public int Mahd { get; set; }
        public string Makh { get; set; }
       // public string Manv { get; set; }
        public string Mask { get; set; }
        public DateTime Ngayhd { get; set; }
        public string Nguoinhan { get; set; }
        public string nhanvienmanv { get; set; }
        public string Sdt { get; set; }
        public string Diachigiaohang { get; set; }
        public long? Tongtien { get; set; }
        public long? Thanhtien { get; set; }
        public int Trangthai { get; set; }
        public virtual Khachhang MakhNavigation { get; set; }
       // public virtual Nhanvien ManvNavigation { get; set; }
        public virtual Sukien MaskNavigation { get; set; }
        public virtual ICollection<Cthd> Cthd { get; set; }
    }
}

DoAn_CuaHangLaptop/Test/Areas/Admin/Controllers/HoaDonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Test.Data;
using Test.Models;


namespace Test.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HoaDonController : Controller
    {
        private readonly LapTopContext _context;

        public HoaDonController(LapTopContext context)
        {
            _context = context;
        }

        // GET: Admin/HoaDon
        public IActionResult Index(int trangthai)
        {
            trangthai--;
            List<Hoadon> dsHd = new List<Hoadon>();
            if (trangthai == -1)
            {
                var query = from hd in _context.Hoadon select hd;
                dsHd = query.ToList();
            }
            else if (trangthai == 0)
            {
                var query = from hd in _context.Hoadon where hd.Trangthai == 0 select hd;
                dsHd = query.ToList();
            }
            else if (trangthai == 1)
            {
                var query = from hd in _context.Hoadon where hd.Trangthai == 1 select hd;
                dsHd = query.ToList();
            }
            else if (trangthai == 2)
            {
                var query = from hd in _context.Hoadon where hd.Trangthai == 2 select hd;
                dsHd = query.ToList();
            }
            else
            {
                var query = from hd in _context.Hoadon where hd.Trangthai == 3 select hd;
                dsHd = query.ToList();
            }
            return View(dsHd);

        }
        // GET: Admin/HoaDon/Details/5
        //public async Task<IActionResult> Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var cthd = await _context.Cthd
        //        .Include(c => c.MahdNavigation)
        //        .FirstOrDefaultAsync(m => m.Mahd == id);
        //    if (cthd == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(cthd);
        //}

        public IActionResult Details(int id)
        {

            List<Cthd> listdata = _context.Cthd.Where(cthd => cthd.Mahd == id).Select(cthd => new Cthd
            {
                Mahd = cthd.Mahd,
                Masp = cthd.Masp,
                MahdNavigation = cthd.MahdNavigation,
                MaspNavigation = cthd.MaspNavigation,
                Soluong = cthd.Soluong,

            }).ToList();
            foreach(var ct in listdata)
            {
                TempData["TongCong"] = ct.MahdNavigation.Tongtien?.ToString("#,##0 VND");
            }
            return View(listdata);
        }
        public IActionResult changeStatus(int mahd)
        {
            Hoadon result = (from hd in _context.Hoadon
                             where hd.Mahd == mahd
                             select hd).SingleOrDefault();

            result.Trangthai++;

            _context.SaveChanges();
            return RedirectToAction("Index", new { trangthai = 0 });
        }
        
        public IActionResult ThongKe()
        {

            return View();
        }
        public IActionResult ThongKePost(int input_nam)
        {
            List<Sanpham> listTK = (from temp in (from hd in _context.Hoadon
                                                  join cthd in _context.Cthd on hd.Mahd equals cthd.Mahd
                                                  where hd.Ngayhd.Year == input_nam
                                                  group cthd by cthd.Masp into grp
                                                  select new
                                                  {
                                                      MaSP = grp.Key,
                                                      Soluong = grp.Sum(cthd => cthd.Soluong)
                                                  })
                                    join sp in _context.Sanpham on temp.MaSP equals sp.Masp
                                    select new Sanpham
                                    {
                                        Tensp = sp.Tensp,
                                        Dongia = sp.Dongia,
                                        Soluong = temp.Soluong,
                                    }).ToList();
            ViewBag.Date = DateTime.Now.ToString("dd/MM/yyyy");
            return View(listTK);
            //return Content(input_nam.ToString());
        }

        //// GET: Admin/HoaDon/Create
        //public IActionResult Create()
        //{
        //    ViewData["Makh"] = new SelectList(_context.Khachhang, "Makh", "Makh");
        //    ViewData["Mask"] = new SelectList(_context.Sukien, "Mask", "Mask");
        //    return View();
        //}

        //// POST: Admin/HoaDon/Create
        //// To protect from overposting attacks, enable the specific properties you want to bind to, for 
        //// more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create([Bind("Mahd,Makh,Mask,Ngayhd,Nguoinhan,nhanvienmanv,Sdt,Diachigiaohang,Tongtien,Thanhtien,Trangthai")] Hoadon hoadon)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _context.Add(hoadon);
        //        await _context.SaveChangesAsync();
        //        return RedirectToAction(nameof(Index));
        //    }
        //    ViewData["Makh"] = new SelectList(_context.Khachhang, "Makh", "Makh", hoadon.Makh);
        //    ViewData["Mask"] = new SelectList(_context.Sukien, "Mask", "Mask", hoadon.Mask);
        //    return View(hoadon);
        //}

        //// GET: Admin/HoaDon/Edit/5
        //public async Task<IActionResult> Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var hoadon = await _context.Hoadon.FindAsync(id);
        //    if (hoadon == null)
        //    {
        //        return NotFound();
        //    }
        //    ViewData["Makh"] = new SelectList(_context.Khachhang, "Makh", "Makh", hoadon.Makh);
        //    ViewData["Mask"] = new SelectList(_context.Sukien, "Mask", "Mask", hoadon.Mask);
        //    return View(hoadon);
        //}

        //// POST: Admin/HoaDon/Edit/5
        //// To protect from overposting attacks, enable the specific properties you want to bind to, for 
        //// more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Edit(int id, [Bind("Mahd,Makh,Mask,Ngayhd,Nguoinhan,nhanvienmanv,Sdt,Diachigiaohang,Tongtien,Thanhtien,Trangthai")] Hoadon hoadon)
        //{
        //    if (id != hoadon.Mahd)
        //    {
        //        return NotFound();
        //    }

        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            _context.Update(hoadon);
        //            await _context.SaveChangesAsync();
        //        }
        //        catch (DbUpdateConcurrencyException)
        //        {
        //            if (!HoadonExists(hoadon.Mahd))
        //            {
        //                return NotFound();
        //            }
        //            else
        //            {
        //                throw;
        //            }
        //        }
        //        return RedirectToAction(nameof(Index));
        //    }
        //    ViewData["Makh"] = new SelectList(_context.Khachhang, "Makh", "Makh", hoadon.Makh);
        //    ViewData["Mask"] = new SelectList(_context.Sukien, "Mask", "Mask", hoadon.Mask);
        //    return View(hoadon);
        //}

        //// GET: Admin/HoaDon/Delete/5
        //public async Task<IActionResult> Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var hoadon = await _context.Hoadon
        //        .Include(h => h.MakhNavigation)
        //        .Include(h => h.MaskNavigation)
        //        .FirstOrDefaultAsync(m => m.Mahd == id);
        //    if (hoadon == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(hoadon);
        //}

        //// POST: Admin/HoaDon/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> DeleteConfirmed(int id)
        //{
        //    var hoadon = await _context.Hoadon.FindAsync(id);
        //    _context.Hoadon.Remove(hoadon);
        //    await _context.SaveChangesAsync();
        //    return RedirectToAction(nameof(Index));
        //}

        //private bool HoadonExists(int id)
        //{
        //    return _context.Hoadon.Any(e => e.Mahd == id);
        //}

    }
}

DoAn_CuaHangLaptop/Test/Areas/Admin/Views/HoaDon/Details.cshtml
@model IEnumerable<Test.Models.Cthd>
@{
    ViewData["Title"] = "Details";
}



<div class="container-fluid">

    <!-- Page Heading -->
    <!-- DataTales Example -->
    <div class="card shadow mb-4">

        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Chi tiết hóa đơn</h6>
        </div>

        <p></p>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Mã hóa đơn</th>
                            <th>Tên người nhận</th>
                            <th>Ngày hóa đơn</th>
                            <th>Tên sản phẩm</th>
                            <th>Số lượng</th>
                            <th>Đơn giá</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.Mahd</td>
                                <td>@item.MahdNavigation.Nguoinhan</td>
                                <td>@item.MahdNavigation.Ngayhd.ToString("dd/MM/yyyy")</td>
                                <td>@item.MaspNavigation.Tensp</td>
                                <td>@item.Soluong</td>
                                <td>@item.MaspNavigation.Dongia?.ToString("#,##0 VND")</td>
                            </tr>

                        }
                        <tr></tr>
                    </tbody>
                </table>
                          <div style="display:flex; justify-content:end" >Tổng cộng: @TempData["TongCong"]</div>
            </div>
        </div>
    </div>

<div>
    <a asp-action="Index">Back to List</a>
</div>
</div>


<style>
    table.table-bordered.dataTable tbody td {
        border-bottom-width: thin;
        border-left-width: thin;
    }
    table.table-bordered.dataTable th {
        border-left-width: thin;
    }
</style>

DoAn_CuaHangLaptop/Test/Areas/Admin/Views/HoaDon/Index.cshtml
@model IEnumerable<Test.Models.Hoadon>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">

    <!-- Page Heading -->
    <!-- DataTales Example -->
    <div class="card shadow mb-4">

        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Hóa đơn</h6>
            <div class="d-flex justify-content-end">
                <a asp-action="Index" asp-controller="HoaDon" asp-area="admin" asp-route-trangthai="1" class="btn btn-primary mr-1">
                    Đơn hàng chưa xác nhận
                </a>
                <a asp-action="Index" asp-controller="HoaDon" asp-area="admin" asp-route-trangthai="2" class="btn btn-secondary mr-1">
                    Đơn hàng đã xác nhận
                </a>
                <a asp-action="Index" asp-controller="HoaDon" asp-area="admin" asp-route-trangthai="3" class="btn btn-info mr-1">
                    Đơn hàng đang giao
                </a>
                <a asp-action="Index" asp-controller="HoaDon" asp-area="admin" asp-route-trangthai="4" class="btn btn-success">
                    Đơn hàng đã giao
                </a>
            </div>
        </div>

        <p></p>
        
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>
                                Ngày hóa đơn
                            </th>
                            <th>
                               Người nhận
                            </th>
                            <th>
                                Số điện thoại
                            </th>
                            <th>
                                Địa chỉ giao hàng
                            </th>
                            <th>
                                Tổng tiền
                            </th>
                            <th>
                                Trạng thái
                            </th>
                            <th>
                                Tác vụ
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                        <tr>
                            <td>
                                @item.Ngayhd.ToString("dd/MM/yyyy")
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Nguoinhan)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Sdt)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Diachigiaohang)
                            </td>
                            <td>
                                @item.Tongtien?.ToString("#,##0 VND")
                            </td>

                            @if (@item.Trangthai == 0)
                            {
                                <td>Chưa xác nhận</td>
                            }
                            else if (@item.Trangthai == 1)
                            {
                                <td>Đã xác nhận</td>
                            }
                            else if (@item.Trangthai == 2)
                            {
                                <td>Đang giao hàng</td>
                            }
                            else
                            {
                                <td>Đã giao hàng</td>

                            }

                            <td>
                                <a asp-controller="HoaDon" asp-action="Details" asp-route-id="@item.Mahd" class="btn btn-info">Chi tiết</a>
                                @if (item.Trangthai != 3)
                                {
                                    <a asp-controller="HoaDon" asp-action="changeStatus" asp-route-mahd="@item.Mahd" class="btn btn-warning">Xác nhận đơn hàng</a>
                                }

                            </td>
                        </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>

DoAn_CuaHangLaptop/Test/Areas/Admin/Views/HoaDon/ThongKe.cshtml
@model IEnumerable<Test.Models.Sanpham>
@{
    ViewData["Title"] = "ThongKe";
}

<div class="container-fluid">

    <!-- Page Heading -->
    <!-- DataTales Example -->
    <div class="card shadow mb-4">

        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Thống kê</h6>
        </div>

        <p></p>
       
        <div class="card-body">
            <form action="ThongKePost" >
                @*<div class="form-group">
                    <label for="input_nam">Nhập năm</label>
                    <input type="number" class="form-control" id="input_nam" name="input_nam" required> 
                </div>*@
                <div class="form-group">
                    <label for="input_nam">Nhập năm</label>
                    <select id="input_nam" class="form-control" name="input_nam">
                        <option value="2021" selected>2021</option>
                        <option value="2022">2022</option>
                    </select>
                </div>
                <button type="submit" class="btn btn-primary">Thống kê</button>
            </form>
        </div>
        </div>
    </div>
    

DoAn_CuaHangLaptop/Test/Areas/Admin/Views/HoaDon/ThongKePost.cshtml
@model IEnumerable<Test.Models.Sanpham>
@{
    ViewData["Title"] = "ThongKePost";
}
@section Scripts {
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.8.1/html2pdf.bundle.min.js" integrity="sha512-vDKWohFHe2vkVWXHp3tKvIxxXg0pJxeid5eo+UjdjME3DBFBn2F8yWOE0XmiFcFbXxrEOR1JriWEno5Ckpn15A==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" referrerpolicy="no-referrer"></script>
    <script>
        $("#printPDF").click(function () {
            var element = document.getElementById('invoice-container');
            html2pdf(element)  
        })
    </script>
}
<div class="container-fluid">

    <!-- Page Heading -->
    <!-- DataTales Example -->
    <div class="card shadow mb-4">

        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Thống kê</h6>
        </div>

        <p></p>
        <div class="card-body" id="invoice-container">
            <div class="row align-items-center">
                <div class="col-sm-7 text-sm-start mb-3 mb-sm-0">
                    <div class="sidebar-brand-text mx-3"><strong>LAPTOPSTORE</strong></div>
                </div>
                <div class="col-sm-5 text-center text-sm-end">
                    <h5 class="text-7 mb-0"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Thống kê doanh số trong năm</font></font></h5>
                    <strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Ngày: </font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">@ViewBag.Date</font></font>
                </div>
            </div>
            <table class="table table-bordered ">
                <thead>
                    <tr class="table-warning">
                        <th scope="col">Tên sản phẩm</th>
                        <th scope="col">Số lượng</th>
                        <th scope="col">Đơn giá</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var i in Model)
                    {

                        <tr>
                            <td>@i.Tensp</td>
                            <td>@i.Soluong</td>
                            <td>@i.Dongia?.ToString("#,##0 VND")</td>
                        </tr>
                    }

                </tbody>
            </table>
        </div>
    </div>
    <div class="text-center mt-2">

        <div class="btn-group btn-group-sm d-print-none">
            <a id="printPDF" class="btn btn-success">Xuất PDF</a>
        </div>
    </div>
</div>