DoAn_CuaHangLaptop/Test/Models/Boxuly.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace Test.Models
{
    public partial class Boxuly
    {
        public Boxuly()
        {
            Sanpham = new HashSet<Sanpham>();
        }
        [Display(Name = "Mã bộ xử lý")]
        public string Mabxl { get; set; }
        [Display(Name = "Mã bộ xử lý")]
        public string Congnghecpu { get; set; }
        [Display(Name = "Số nhân")]
        public int? Sonhan { get; set; }
        [Display(Name = "Số luồng")]
        public int? Soluong { get; set; }
        [Display(Name = "Tốc độ CPU")]
        public string Tocdocpu { get; set; }
        [Display(Name = "Tốc độ tối đa")]
        public string Tocdotoida { get; set; }
        [Display(Name = "Bộ nhớ đệm")]
        public string Bonhodem { get; set; }

        public virtual ICollection<Sanpham> Sanpham { get; set; }
    }
}

DoAn_CuaHangLaptop/Test/Areas/Admin/Controllers/BoXuLyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Test.Data;
using Test.Models;

namespace Test.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "admin")]
    public class BoXuLyController : Controller
    {
        private readonly LapTopContext _context;

        public BoXuLyController(LapTopContext context)
        {
            _context = context;
        }

        // GET: Boxuly
        public async Task<IActionResult> Index()
        {
            return View(await _context.Boxuly.ToListAsync());
        }

        // GET: Boxuly/Details/5
        //public async Task<IActionResult> Details(string id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var boxuly = await _context.Boxuly
        //        .FirstOrDefaultAsync(m => m.Mabxl == id);
        //    if (boxuly == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(boxuly);
        //}

        // GET: Boxuly/Create
        //public IActionResult Create()
        //{
        //    return View();
        //}

        // POST: Boxuly/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Mabxl,Congnghecpu,Sonhan,Soluong,Tocdocpu,Tocdotoida,Bonhodem")] Boxuly boxuly)
        {
            if (ModelState.IsValid)
            {
                _context.Add(boxuly);
                await _context.SaveChangesAsync();
                TempData["AlertMessage"] = "Tạo thành công";
                TempData["AlertType"] = "alert alert-success";
                return RedirectToAction(nameof(Index));
            }
            return View(boxuly);
        }

        // GET: Boxuly/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var boxuly = await _context.Boxuly.FindAsync(id);
            if (boxuly == null)
            {
                return NotFound();
            }
            return View(boxuly);
        }

        // POST: Boxuly/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Mabxl,Congnghecpu,Sonhan,Soluong,Tocdocpu,Tocdotoida,Bonhodem")] Boxuly boxuly)
        {
            if (id != boxuly.Mabxl)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(boxuly);
                    await _context.SaveChangesAsync();
                    TempData["AlertMessage"] = "Cập nhật thành công";
                    TempData["AlertType"] = "alert alert-success";
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BoxulyExists(boxuly.Mabxl))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(boxuly);
        }

        // GET: Boxuly/Delete/5
        //public async Task<IActionResult> Delete(string id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var boxuly = await _context.Boxuly
        //        .FirstOrDefaultAsync(m => m.Mabxl == id);
        //    if (boxuly == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(boxuly);
        //}

        // POST: Boxuly/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(string Mabxl)
        {
            try
            {
                var boxuly = await _context.Boxuly.FindAsync(Mabxl);
                _context.Boxuly.Remove(boxuly);
                await _context.SaveChangesAsync();
                TempData["AlertMessage"] = "Xóa thành công";
                TempData["AlertType"] = "alert alert-success";
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                TempData["AlertMessage"] = "Xóa không thành công";
                TempData["AlertType"] = "alert alert-danger";
                return RedirectToAction(nameof(Index));
            }
        }

        private bool BoxulyExists(string id)
        {
            return _context.Boxuly.Any(e => e.Mabxl == id);
        }

        [HttpPost]
        public JsonResult timBoXuLy(string id)
        {
            var bxl = _context.Boxuly.Find(id); ;
            return Json(bxl);
        }
    }
}

DoAn_CuaHangLaptop/Test/Areas/Admin/Pages/Role/edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Test.Data;

namespace App.Admin.Role
{
    [Authorize(Roles = "admin")]

    public class EditModel : RolePageModel
    {
        public EditModel(RoleManager<IdentityRole> roleManager, LapTopContext myBlogContext) : base(roleManager, myBlogContext)
        {

        }

        public class InputModel
        {
            [Display(Name = "Tên của role")]
            [Required(ErrorMessage = "Phải nhập {0}")]
            [StringLength(256, MinimumLength = 3, ErrorMessage = "{0} phải dài {2} đến {1} ký tự")]
            public string Name { get; set; }
        }

        [BindProperty]
        public InputModel Input { set; get; }

        public IdentityRole role { get; set; }

        public async Task<IActionResult> OnGet(string roleid)
        {
            if (roleid == null) return NotFound("Không tìm thấy role");

            role = await _roleManager.FindByIdAsync(roleid);
            if (role != null)
            {
                Input = new InputModel()
                {
                    Name = role.Name
                };
                return Page();
            }
            return NotFound("Không tìm thấy role");
        }



        public async Task<IActionResult> OnPostAsync(string roleid)
        {
            if (roleid == null) return NotFound("Không tìm thấy role");
            role = await _roleManager.FindByIdAsync(roleid);
            if (role == null) return NotFound("Không tìm thấy role");
            if (!ModelState.IsValid)
            {
                return Page();
            }

            role.Name = Input.Name;
            // luu ket qua cap nhat trong result
            var result = await _roleManager.UpdateAsync(role);

            if (result.Succeeded)
            {
                StatusMessage = $"Bạn vừa đổi tên: {Input.Name}";
                return RedirectToPage("./Index");
            }
            else
            {
                result.Errors.ToList().ForEach(error => {
                    ModelState.AddModelError(string.Empty, error.Description);
                });
            }
            return Page();
        }
    }
}

DoAn_CuaHangLaptop/Test/Controllers/BoxulyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Test.Data;
using Test.Models;

namespace Test.Controllers
{
    public class BoxulyController : Controller
    {
        private readonly LapTopContext _context;

        public BoxulyController(LapTopContext context)
        {
            _context = context;
        }

        // GET: Boxuly
        public async Task<IActionResult> Index()
        {
            return View(await _context.Boxuly.ToListAsync());
        }

        // GET: Boxuly/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var boxuly = await _context.Boxuly
                .FirstOrDefaultAsync(m => m.Mabxl == id);
            if (boxuly == null)
            {
                return NotFound();
            }

            return View(boxuly);
        }

        // GET: Boxuly/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Boxuly/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Mabxl,Congnghecpu,Sonhan,Soluong,Tocdocpu,Tocdotoida,Bonhodem")] Boxuly boxuly)
        {
            if (ModelState.IsValid)
            {
                _context.Add(boxuly);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(boxuly);
        }

        // GET: Boxuly/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var boxuly = await _context.Boxuly.FindAsync(id);
            if (boxuly == null)
            {
                return NotFound();
            }
            return View(boxuly);
        }

        // POST: Boxuly/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Mabxl,Congnghecpu,Sonhan,Soluong,Tocdocpu,Tocdotoida,Bonhodem")] Boxuly boxuly)
        {
            if (id != boxuly.Mabxl)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(boxuly);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BoxulyExists(boxuly.Mabxl))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(boxuly);
        }

        // GET: Boxuly/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var boxuly = await _context.Boxuly
                .FirstOrDefaultAsync(m => m.Mabxl == id);
            if (boxuly == null)
            {
                return NotFound();
            }

            return View(boxuly);
        }

        // POST: Boxuly/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var boxuly = await _context.Boxuly.FindAsync(id);
            _context.Boxuly.Remove(boxuly);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BoxulyExists(string id)
        {
            return _context.Boxuly.Any(e => e.Mabxl == id);
        }
    }
}

DoAn_CuaHangLaptop/Test/Areas/Admin/Views/BoXuLy/Edit.cshtml
@model Test.Models.Boxuly

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h1>Cập nhật</h1>

<h4>Bộ xử lý</h4>
<hr />
<div class="row" style="display:flex;justify-content:center">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Mabxl" />
            <div class="form-group">
                <label asp-for="Congnghecpu" class="control-label"></label>
                <input asp-for="Congnghecpu" class="form-control" />
                <span asp-validation-for="Congnghecpu" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sonhan" class="control-label"></label>
                <input asp-for="Sonhan" class="form-control" />
                <span asp-validation-for="Sonhan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Soluong" class="control-label"></label>
                <input asp-for="Soluong" class="form-control" />
                <span asp-validation-for="Soluong" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tocdocpu" class="control-label"></label>
                <input asp-for="Tocdocpu" class="form-control" />
                <span asp-validation-for="Tocdocpu" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tocdotoida" class="control-label"></label>
                <input asp-for="Tocdotoida" class="form-control" />
                <span asp-validation-for="Tocdotoida" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Bonhodem" class="control-label"></label>
                <input asp-for="Bonhodem" class="form-control" />
                <span asp-validation-for="Bonhodem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Lưu" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="mt-3">Trở về trang danh sách</a>
</div>

DoAn_CuaHangLaptop/Test/Areas/Admin/Views/BoXuLy/Index.cshtml
@model IEnumerable<Test.Models.Boxuly>
@{
    Layout = "_Layout";
}
@section Scripts{
    <script>
    setTimeout(function () {
        $('#msgA').fadeOut('slow');
    }, 2000);
    $('table .delete').on('click', function () {
        var id = $(this).data("id");
            $.ajax({
                type: 'POST',
                url: '@Url.Action("timBoXuLy")',
                data: { "id": id },
                success: function (response) {
                    console.log(response)
                    $("#DeleteRecord #mabxl").val(response.mabxl);
                    $("#DeleteRecord #Congnghecpu").val(response.congnghecpu);
                    $("#DeleteRecord #Sonhan").val(response.sonhan);
                    $("#DeleteRecord #Soluong").val(response.soluong);
                    $("#DeleteRecord #Tocdocpu").val(response.tocdocpu);
                }
            })
    })
    </script>
}
<div class="container-fluid">

    <!-- Page Heading -->
    <!-- DataTales Example -->
    <div class="card shadow mb-4">

        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Bộ xử lý</h6>
        </div>

        <p></p>

        <div class="container">

            <div class="row">
                <div class="col-md-12">
                    <form asp-action="Create" method="post">
                        <input type="hidden" class="form-control" id="Mabxl" name="Mabxl" value="1">
                        <div class="form-row">
                            <div class="form-group col-md-2">
                                <label>Số nhân</label>
                                <input type="number" class="form-control" id="Sonhan" name="Sonhan">
                            </div>
                            <div class="form-group col-md-2">
                                <label for="Soluong">Số luồng</label>
                                <input type="number" class="form-control" id="Soluong" name="Soluong">
                            </div>
                            <div class="form-group col-md-3">
                                <label for="Tocdocpu">Tốc độ CPU</label>
                                <input type="text" class="form-control" id="Tocdocpu" name="Tocdocpu">
                            </div>
                            <div class="form-group col-md-3">
                                <label for="Tocdotoida">Tốc độ tối đa</label>
                                <input type="text" class="form-control" id="Tocdotoida" name="Tocdotoida">
                            </div>
                            <div class="form-group col-md-2">
                                <label for="Bonhodem">Bộ nhớ đệm</label>
                                <input type="text" class="form-control" id="Bonhodem" name="Bonhodem">
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <label for="Congnghecpu">Công nghệ CPU</label>
                                <textarea class="form-control" id="Congnghecpu" name="Congnghecpu" rows="3"></textarea>
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="form-group col-md-10"></div>
                            <div class="form-group col-md-2">
                                <button type="submit" class="btn btn-primary">Thêm</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        @if (TempData["AlertMessage"] != null)
        {
            <div id="msgA" class="@TempData["AlertType"]" role="alert">
                @TempData["AlertMessage"]
            </div>
        }
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th width="15%">Công nghệ CPU</th>
                            <th width="7%">Số nhân</th>
                            <th width="7%">Số luồng</th>
                            <th width="10%">Tốc độ CPU</th>
                            <th width="16%">Tốc độ tối đa</th>
                            <th width="10%">Bộ nhớ đệm</th>
                            <th width="20%">Tác vụ</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                        <tr>
                            <td>@item.Congnghecpu</td>
                            <td>@item.Sonhan</td>
                            <td>@item.Soluong</td>
                            <td>@item.Tocdocpu</td>
                            <td>@item.Tocdotoida</td>
                            <td>@item.Bonhodem</td>
                            <td>
                                <a asp-action="Edit" asp-route-id="@item.Mabxl" class="btn btn-secondary">Cập nhật</a>
                                <button type="button"
                                        class="btn btn-danger delete"
                                        data-toggle="modal"
                                        data-target="#DeleteRecord"
                                        data-id="@item.Mabxl">
                                    Xóa
                                </button>
                            </td>
                        </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="DeleteRecord" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Xác nhận xóa</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form asp-controller="BoXuLy" asp-action="Delete" method="post">
                <div class="modal-body">
                    <div class="form-group">
                        <input type="hidden" readonly id=mabxl class="form-control" name="Mabxl" />

                        <div class="form-group row">
                            <label class="col-sm-4 col-form-label">Công nghệ CPU</label>
                            <div class="col-sm-8">
                                <input type="text" readonly id="Congnghecpu" class="form-control" name="Congnghecpu" />
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-sm-4 col-form-label">Số nhân</label>
                            <div class="col-sm-8">
                                <input type="text" readonly id="Sonhan" class="form-control" name="Sonhan" />
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-sm-4 col-form-label">Số luồng</label>
                            <div class="col-sm-8">
                                <input type="text" readonly id="Soluong" class="form-control" name="Soluong" />
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-sm-4 col-form-label">Tốc độ CPU</label>
                            <div class="col-sm-8">
                                <input type="text" readonly id="Tocdocpu" class="form-control" name="Tocdocpu" />
                            </div>
                        </div>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Đóng</button>

                    <button type="submit" class="btn btn-primary">Xóa</button>
                </div>
            </form>
        </div>
    </div>
</div>